### ISSUE TITLE
Is AGLint supposed to throw an error for forbidden class names?

### ISSUE THREAD

**Issue by royhadad** [AdguardTeam/AGLint#209]
I have this scss file alongside a react component file with the following class name:
```scss
.ad {
  color: red;
}
```
```js
const MyComponent = () => (
    <div className='ad'>
      hello world
    </div>
);
```

running AGLint on it, yet no problems found:
```bash
npx aglint ./my-file.scss
npx aglint ./my-component.jsx
```

common adblockers will block this element from the browser, by applying a `display: none` css property to it.

My question is as follows: 
**Is AGLint supposed to throw an error for those kind of problems? Or did I completely miss the point of the linter?**

**Comment by scripthunter7** [comment]
Hi @royhadad, ONLY adblock filter lists can be linted with AGLint (like [this](https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/adservers_firstparty.txt)), CSS / JSX files are NOT supported by AGLint. I can recommend Stylelint or ESLint for that.

**Comment by royhadad** [comment]
> Hi @royhadad, ONLY adblock filter lists can be linted with AGLint (like [this](https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/adservers_firstparty.txt)), CSS / JSX files are NOT supported by AGLint. I can recommend Stylelint or ESLint for that.

Thanks for the reply, are you aware by any chance of any Stylelint or ESLint plugin that does this?

**Comment by scripthunter7** [comment]
I'm not sure I fully understand what exactly you want, could you please elaborate it a little more?

**Comment by royhadad** [comment]
@scripthunter7 Yeah, sure.

I had this bug in my website, where certain elements had a classname "advertiser", in production my adblock plugin blocked those elements from appearing.
What I'm lookin for is some sort of linter to scan my codebase for these kind of class names.

**Comment by scripthunter7** [comment]
You probably need to configure a Stylelint rule (e.g. [this one](https://stylelint.io/user-guide/rules/selector-class-pattern/)) to exclude some class patterns

**Comment by royhadad** [comment]
found it! Very niche, only a few github stars 
https://github.com/wuhonglei/stylelint-config-adblock
