### ISSUE TITLE
Add minkou.jp/js/tracking.js to banned rule

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AGLint#221]
https://github.com/AdguardTeam/AdguardFilters/commit/2708e1db566776b9a1c0af3a0752ee23e1cdd9fb

**Comment by scripthunter7** [comment]
@Yuki2718 I think its enough to add these rules to the linter config in our filters repo: https://github.com/AdguardTeam/AdguardFilters/blob/c10fd90a992fe837c9671d86b91e38f00009b62d/.aglintrc.yaml#L10-L12
