### ISSUE TITLE
A problem with regexp in $$ rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AGLint#223]
![image](https://github.com/user-attachments/assets/60bea9c3-02ce-4ce0-b052-a102ed1e0ddb)
```
wiki.yjsnpi.nu$$script:contains(/\+['"`]\w.+catch/)
```

**Comment by Alex-302** [comment]
Ok, will move.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/VscodeAdblockSyntax/issues/140

**Comment by scripthunter7** [comment]
thank you
