### ISSUE TITLE
Adding support for ABP CSS injections

### ISSUE THREAD

**Issue by monzta** [AdguardTeam/AGLint#224]
`euronews.com###o-site-hr__leaderboard-wallpaper.u-show-for-xlarge {remove:true;}` added in https://github.com/easylist/easylist/commit/99c717f stated to throw errors: https://github.com/easylist/easylist/actions/runs/11801052352/job/32873439085 

Seems it doesn't know ABP syntax of `{remove:true;}`.

**Comment by ameshkov** [comment]
Uh, can ABP consider using a different marker for these rules?

Here's the version compatible with AdGuard and uBO:
`euronews.com#$##o-site-hr__leaderboard-wallpaper.u-show-for-xlarge {remove:true;} `

**Comment by monzta** [comment]
Oh, `#$#` is already reserved for [snippet filters](https://help.adblockplus.org/hc/en-us/articles/1500002338501-Snippet-filters-tutorial). :/

**Comment by scripthunter7** [comment]
You can disable AGLint for that line temporarily: https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#ignore-single-adblock-rule

**Comment by monzta** [comment]
Oh yeah, it's only mentioned [here](https://help.adblockplus.org/hc/en-us/articles/360062733293-How-to-write-filters#snippets) and it links to the page I linked.

@scripthunter7 Great, thanks!

**Comment by ameshkov** [comment]
@monzta no I meant the `{remove:true}` syntax, can't find it anywhere

**Comment by monzta** [comment]
@ameshkov oh, of course 🤦🏻‍♂️ This hasn't been added there yet. I'll take care of it.

**Comment by scripthunter7** [comment]
@ameshkov Opened issues in tsurlfilter and CL

**Comment by monzta** [comment]
fyi `#?#` filters like `example.org#?#div:-abp-has(> div:-abp-properties(width: 44px)) {remove: true;}`

**Comment by scripthunter7** [comment]
@monzta thank you, added to issues

**Comment by ameshkov** [comment]
@monzta it seems that it's not just `remove: true`?
https://www.abptestpages.org/en/abp-testcase-subscription.txt

I see this as well:
```
abptestpages.org##.testcase-inline-css-ehe {background-color: #c70d2c;}
abptestpages.org#@#.testcase-inline-css-ehe
```

**Comment by monzta** [comment]
@ameshkov You are right. Note that these currently only work for privileged filter lists in ABP.

**Comment by Yuki2718** [comment]
As mentioned in Slack, the syntax is documented in relase notes
https://gitlab.com/eyeo/adblockplus/abc/webext-ad-filtering-solution/-/releases/1.3.0
https://gitlab.com/eyeo/adblockplus/abc/webext-ad-filtering-solution/-/releases/1.4.0

**Comment by Yuki2718** [comment]
> You are right. Note that these currently only work for privileged filter lists in ABP.

Does that mean EL is now privileged? I thought in ABP only ABP filter is privileged.

**Comment by monzta** [comment]
No, ABP Filters only for CSS inline styles. `remove` works on any list.

**Comment by monzta** [comment]
@scripthunter7 Sure, done.
