### ISSUE TITLE
TypeError: select is not a function

### ISSUE THREAD

**Issue by spirillen** [AdguardTeam/AGLint#225]
Hi, first of, I'm not into node, docker, podman and likes 😒 

So running `npx aglint init` in the root folder of my project return an error, which is as well could be on the dark side of the moon

```
npx aglint init
Oops! Something went wrong! :(

AGLint: 2.1.1

select is not a function

  TypeError: select is not a function
      at createConfig (/$somePATH/adblocker-rules/node_modules/@adguard/aglint/dist/aglint.cli.js:141:32)
      at /$somePATH/adblocker-rules/node_modules/@adguard/aglint/dist/aglint.cli.js:217:19
```

Anyone who could help me here?

**Comment by scripthunter7** [comment]
@spirillen Thank you, fixed in 2.1.2
