### ISSUE TITLE
detect invalid cosmetic filter ##selector|example.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AGLint#229]
`##.twitter-timeline|blog.jp` is not flagged as an invalid filter: https://github.com/AdguardTeam/AdguardFilters/commit/051ef5aabaab333fa6ab21d5df869f9a1d4aa6d9

**Comment by scripthunter7** [comment]
Interesting, CSSTree parses it as 

- class selector `.twitter-timeline`
- [type selector ](https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors)`|blog`
- class selector `.jp`
